import { HousekeepingBoardRoom, HousekeepingSummary, CheckpointItem, MinibarItemAudit, LinenTurnaroundAction, MaintenanceEscalationPayload } from './types';
import { RoomStatus } from '@spicehub/shared-types';
export type HousekeepingStoreListener = () => void;
export declare class HousekeepingStore {
    private rooms;
    private summary;
    private selectedFloor;
    private statusFilter;
    private searchQuery;
    private selectedRoom;
    private isAttendantModalOpen;
    private isInspectionModalOpen;
    private isMaintenanceModalOpen;
    private activeChecklist;
    private activeMinibarAudit;
    private activeLinenAction;
    private inspectionNotes;
    private maintenanceDraft;
    private ecoTuckInCount;
    private isLoading;
    private error;
    private listeners;
    constructor(initialRooms?: HousekeepingBoardRoom[]);
    subscribe(listener: HousekeepingStoreListener): () => void;
    private notify;
    setBoardData(rooms: HousekeepingBoardRoom[], summary?: HousekeepingSummary): void;
    private recomputeSummary;
    getSummary(): HousekeepingSummary;
    getFloors(): number[];
    getSelectedFloor(): number | 'ALL';
    filterByFloor(floor: number | 'ALL'): void;
    getStatusFilter(): RoomStatus | 'ALL';
    filterByStatus(status: RoomStatus | 'ALL'): void;
    getSearchQuery(): string;
    setSearchQuery(q: string): void;
    getFilteredRooms(): HousekeepingBoardRoom[];
    getSelectedRoom(): HousekeepingBoardRoom | null;
    openAttendantModal(room: HousekeepingBoardRoom): void;
    closeAttendantModal(): void;
    isAttendantModalActive(): boolean;
    getActiveChecklist(): CheckpointItem[];
    toggleChecklistItem(index: number): void;
    getActiveMinibarAudit(): MinibarItemAudit[];
    updateMinibarQuantity(id: string, delta: number): void;
    getActiveLinenAction(): LinenTurnaroundAction;
    setLinenAction(action: LinenTurnaroundAction): void;
    openInspectionModal(room: HousekeepingBoardRoom): void;
    closeInspectionModal(): void;
    isInspectionModalActive(): boolean;
    getInspectionNotes(): string;
    setInspectionNotes(notes: string): void;
    openMaintenanceModal(room: HousekeepingBoardRoom): void;
    closeMaintenanceModal(): void;
    isMaintenanceModalActive(): boolean;
    getMaintenanceDraft(): MaintenanceEscalationPayload;
    updateMaintenanceDraft(patch: Partial<MaintenanceEscalationPayload>): void;
    getEcoWaterSavings(): {
        liters: number;
        kwhSaved: number;
    };
    getMinibarAuditTotal(): number;
    setLoading(loading: boolean): void;
    getLoading(): boolean;
    setError(error: string | null): void;
    getError(): string | null;
}
