import { ReservationTabMode, TableReservationDTO, TableReservationSummary, RoomArrivalBookingDTO, RoomArrivalsSummary, CleanRoomOption, TableReservationStatus } from './types';
export type ReservationStoreListener = () => void;
export declare class ReservationStore {
    private tabMode;
    private selectedDate;
    private tableReservations;
    private tableSummary;
    private diningStatusFilter;
    private roomArrivals;
    private arrivalsSummary;
    private availableCleanRooms;
    private roomFilter;
    private searchQuery;
    private isNewDiningModalOpen;
    private isAssignRoomModalOpen;
    private selectedBookingForAssign;
    private selectedReservationForAction;
    private isLoading;
    private error;
    private listeners;
    constructor();
    subscribe(listener: ReservationStoreListener): () => void;
    private notify;
    getTabMode(): ReservationTabMode;
    setTabMode(mode: ReservationTabMode): void;
    getSelectedDate(): string;
    setSelectedDate(date: string): void;
    setTableData(reservations: TableReservationDTO[], summary?: TableReservationSummary): void;
    private recomputeTableSummary;
    getTableSummary(): TableReservationSummary;
    getDiningStatusFilter(): TableReservationStatus | 'ALL';
    setDiningStatusFilter(status: TableReservationStatus | 'ALL'): void;
    getFilteredDiningReservations(): TableReservationDTO[];
    setArrivalsData(bookings: RoomArrivalBookingDTO[], summary?: RoomArrivalsSummary, cleanRooms?: CleanRoomOption[]): void;
    getArrivalsSummary(): RoomArrivalsSummary;
    getAvailableCleanRooms(): CleanRoomOption[];
    getRoomFilter(): 'ALL' | 'ARRIVALS' | 'DEPARTURES' | 'UNASSIGNED' | 'IN_HOUSE';
    setRoomFilter(filter: 'ALL' | 'ARRIVALS' | 'DEPARTURES' | 'UNASSIGNED' | 'IN_HOUSE'): void;
    getFilteredRoomArrivals(): RoomArrivalBookingDTO[];
    getSearchQuery(): string;
    setSearchQuery(q: string): void;
    openNewDiningModal(): void;
    closeNewDiningModal(): void;
    isNewDiningModalActive(): boolean;
    openAssignRoomModal(booking: RoomArrivalBookingDTO): void;
    closeAssignRoomModal(): void;
    isAssignRoomModalActive(): boolean;
    getSelectedBookingForAssign(): RoomArrivalBookingDTO | null;
    setLoading(loading: boolean): void;
    getLoading(): boolean;
    setError(error: string | null): void;
    getError(): string | null;
}
